[package]
name = "graph-editor-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.31.0", features = ["persistence"] }
egui_extras = "0.31.0"
egui-file-dialog = "0.9.0"
rand = "0.9.0"
serde = "1"
serde_json = "1"